### ISSUE TITLE
Feedback from documentation authors

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/jsxtreme-markdown#12]
@mapbox/support & @katydecorah, as authors of many Jekyll pages, I'd love your feedback on this. 

This module enables the Markdown syntax that we'll use in [Batfish](https://github.com/mapbox/batfish/) — the React-powered static-site generator we'll use to build some sites. It allows for interpolated JS expressions and React elements within delimiters — defaults are `{{..}}`. I think this should allow for all the powers we get with Liquid templates, and some more. It will be especially nice to be able to interpolate React elements, instead of repeating HTML.

[The example for `toJsx`](https://github.com/mapbox/jsxtreme-markdown#tojsx) shows how a Markdown document with interpolation might look.

So I'm just pinging you to see what you think! Do you foresee any shortcomings or have any questions about this syntax? Do you think it will do the job?

**Comment by katydecorah** [comment]
@davidtheclark ohh thank you for this!

Would it be possible to automatically add an id to headline where the value is the text slugified? For example:

```html
<h1 id='my-cool-title'>My cool title</h1>
```

This is a markdown setting we use for Help pages and allows us to deep link, especially via a sidebar/table of contents.

That's the only feature that jumps out at me at the moment. I'll keep my eye out for more things like this!

**Comment by davidtheclark** [comment]
@katydecorah: yeah, looks like there's a remark plugin already that should do this: https://github.com/ben-eb/remark-autolink-headings. I could include this as a default in either Batfish or our Mapbox-specific wrapper of Batfish.

**Comment by katydecorah** [comment]
@davidtheclark thought of another one!

Does the module support back ticks for code blocks and for identifying the type of code for syntax highlighting? For example:

![image](https://user-images.githubusercontent.com/2180540/27541466-ff9e3736-5a51-11e7-97a4-4e9ec5e58f32.png)

We use this a lot in help docs.

**Comment by davidtheclark** [comment]
@katydecorah: Yep, definitely. This will be supported with a rehype plugin. I'm trying to figure out the best syntax highlighter for us: https://github.com/mapbox/jsxtreme-markdown/issues/10. Any input welcome.
