### ISSUE TITLE
What is the use-case for a custom default template?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/jsxtreme-markdown#13]
Based on how jsxtreme-markdown readme promotes custom templates, it made me think that it would be a commonly used and useful option. However, the template contains most of the core logic behind this project and makes reasonable choices. I would de-emphasize customizing the default template in docs, 99% of the time I doubt users would want to customize this.

**Comment by davidtheclark** [comment]
> the template contains most of the core logic behind this project

I don't think that's the case. The core logic in this project is transforming Markdown to JSX — the template is just extra frosting that translates that JSX directly into a React component for you, with, as you say, reasonable choices.

> I would de-emphasize customizing the default template in docs

In ecbb2c2 I removed the bold on that sentence.

> I doubt users would want to customize this

A common problem I've found in modules with similar functionality (i.e. transformation) is that a lack of this type of option. I think a template API does not add much complexity but allows for broad extensibility, which makes the module more useful.
