### ISSUE TITLE
A simple ASCII diagram of the relationship between toJsx and toComponentModule ?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/jsxtreme-markdown#14]
It took me a second to wrap my head around the architecture behind this project. It is very elegant, but the idea that the output of toComponentModule exists to then be passed through toJsx for some reason took me a minute to grasp

``` 
post.md -> toComponentModule() -> component with inlined markdown -> toJsx() -> HTML page
```

**Comment by davidtheclark** [comment]
Seems there's been a misunderstanding. You should have to use *both* `toComponentModule` and `toJsx`. `toComponentModule` actually uses `toJsx` internally. And you never get HTML as output — only React code — either JSX (from `toJsx`) or a React component module (from `toComponentModule`).

```
markdown -> toJsx() -> JSX -> do something with JSX
```

```
markdown -> toComponentModule() -> React component module -> import the module and render it in your React code
```

**Comment by samanpwbb** [comment]
Yep, I see that I am wrong. I'm trying to think of what tripped me up... The documentation is pretty clear, I just misread it.
