### ISSUE TITLE
Make a REPL page

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/jsxtreme-markdown#17]
If all the dependencies can run in the browser, this should be a fairly straightforward project and will really help people understand the module.

**Comment by davidtheclark** [comment]
I got a little prototype of this working. It loads like 10 MB into the browser —— I think because of Babel packages? [The Babel REPL](https://babeljs.io/repl/) isn't nearly that heavy, though. Maybe we just need to dig in more and figure out what's going on.

If we can't get a reasonable bundle, another possibility (fun side project for learning about AWS, @jfurrow @lshig) would be to create a Lambda-powered API that we can call to perform the transformation.

**Comment by jfurrow** [comment]
This is a cool idea!

**Comment by davidtheclark** [comment]
The REPL is live! https://mapbox.github.io/jsxtreme-markdown/
