### ISSUE TITLE
Change "modules" frontmatter to "prependJs"

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/jsxtreme-markdown#18]
Here are the `modules` docs:

> modules {?Array<string>} - An array of lines of JS code that require or import modules that will be used in the interpolated JS and JSX. This value can be overridden document-by-document by setting modules in the front matter of specific documents.

I don't know if `modules` is the right name here ... I can think of two other approaches that might be better:

- `imports`, `importLines`: This might make it more clear that you're not just naming modules (e.g. `'react'`) but writing lines of JavaScript (e.g. `import React from 'react';`).
- `prependJs`: This name exposes the fact that you can actually write whatever JS you want in these lines. You should use the feature for importing modules, but you could also use it for performing a calculation, setting up a variable, etc.

@mapbox/frontend looking for some naming help here.

**Comment by tristen** [comment]
I like `import` singular personally. GO uses that singular keyword to add multiple packages.

**Comment by jfurrow** [comment]
I vote for `prependJs`, or something similar, due to it being a string of text that gets evaluated.

**Comment by davidtheclark** [comment]
Split vote ... I think I'll go with `prependJs` since it's most accurate and flexible.

**Comment by tristen** [comment]
I change my vote to `prependJs` 😛
