### ISSUE TITLE
Consider changing Babel plugin to a babel-macro

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/jsxtreme-markdown#25]
[babel-macros](https://github.com/kentcdodds/babel-macros) aims to introduce a standard interface for performing this kind of transformation. I read about it in [a post on the Babel blog](https://babeljs.io/blog/2017/09/11/zero-config-with-babel-macros).

babel-macros itself provides the code to parse `import` and `require` statements and figure out the references to those bindings. Then the macro itself only needs to worry about its particular transformation. 

I can only see two downsides to converting jsxtreme-markdown's Babel plugin to a macro:

- https://github.com/kentcdodds/babel-macros/issues/26 — I'm not sure about babel-macros' approach to configuring macros.
- We'd give up the `packageName` option. I think that's totally fine (though it would be a breaking change for Batfish — not a significant one).

@jfurrow what do you think?

(Also, this can provide some good context in the article you're writing. Seems "macro" is the right term for what this Babel plugin is doing!)

**Comment by jfurrow** [comment]
@davidtheclark Sorry, I dropped the ball on this one.

**Comment by davidtheclark** [comment]
I've decided not to do this for now. Someone could create a macro, though, by building off the existing low-level tools.
