### ISSUE TITLE
Sample repo?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/jsxtreme-markdown#26]
Is there a sample repo implementing these modules anywhere yet? Thinking something along the lines of https://github.com/prose/starter

**Comment by davidtheclark** [comment]
:wave: @mikemorris. I'm not sure what a sample repo would contain since these modules can be used in a variety of ways. Is there anything specific you have in mind?

**Comment by mikemorris** [comment]
👋 @davidtheclark Thinking mostly a boilerplate repo that would show how to use these modules alongside a static site generator with any necessary CI build scripts for something like a simple static site pulling in one React component in a Markdown file.

https://blog.mapbox.com/introducing-jsxtreme-markdown-a64c6b404596 mentions many Mapbox sites are already using this, are you using it with Jekyll or some other build process?

**Comment by davidtheclark** [comment]
[Batfish](https://github.com/mapbox/batfish/) is a static-site generator we're using that provides jsxtreme-markdown support through the loader and Babel plugin.

If you're setting up a Webpack build, jsxtreme-markdown-loader should work like other Webpack loaders. And if you're not using Webpack but do have Babel running, babel-plugin-transform-jsxtreme-markdown should allow you to transform your Markdown strings into JSX at build time.

Maybe that helps?

**Comment by mikemorris** [comment]
https://github.com/mapbox/batfish/tree/master/examples/basic is exactly what I was looking for, thanks @davidtheclark!
