### ISSUE TITLE
Sample project for loader?

### ISSUE THREAD

**Issue by spelunk** [mapbox/jsxtreme-markdown#31]
Looking for a very simple webpack config js and app that uses `@mapbox/jsxtreme-markdown-loader`.  The README https://github.com/mapbox/jsxtreme-markdown/tree/master/packages/jsxtreme-markdown-loader#readme is sparse on usage details

**Comment by davidtheclark** [comment]
@spelunk I'm not sure what we would provide that is not documented in the linked Webpack docs: https://webpack.js.org/concepts/loaders/. We could add this, if it helps:

```
 module: {
    rules: [
      {
        test: /\.md$/,
        use: [
          { loader: '@mapbox/jsxtreme-markdown-loader' }
        ]
      }
    ]
  }
```

I don't think adding a complete sample should be necessary in the documentation of every Webpack loader, though. Is there anything more focused you think would help?
