### ISSUE TITLE
support babel-macros

### ISSUE THREAD

**Issue by graingert** [mapbox/jsxtreme-markdown#33]

**Comment by davidtheclark** [comment]
@graingert: The Babel plugin is not a babel-macros macro. It's a regular Babel plugin. So I'm not sure what we would document. Is there something specific you're looking for?

**Comment by graingert** [comment]
ah I thought this added babel-macro support: https://github.com/mapbox/jsxtreme-markdown/pull/27

**Comment by graingert** [comment]
@davidtheclark updated doc

**Comment by davidtheclark** [comment]
Ah, I understand. I got some ideas for improving the code, but did not make it fit the babel-macros interface.

**Comment by graingert** [comment]
@davidtheclark I've added you as an owner on https://www.npmjs.com/package/md.macro as I think that would be a neat name for it.

**Comment by graingert** [comment]
then you get:
```js
import md from 'babel-plugin-transform-jsxtreme-markdown/md';

**Comment by davidtheclark** [comment]
@graingert I'm not sure what you're aiming for. Would you mind clarifying your thoughts? Sorry I closed https://github.com/mapbox/jsxtreme-markdown/issues/25 without an explanation — so I just added one. I decided against changing the Babel plugin into a macro, but it should be straightforward for someone (maybe you?) to build a macro package using the packages that exist. Then we'll have both: the regular Babel plugin and the macro. Would you like to take that on? If so, I'd prefer that it live outside this monorepo, at least for some period of time; and then we can assess whether to pull it in. Does that sound good?
