### ISSUE TITLE
Cannot find module 'prettier'

### ISSUE THREAD

**Issue by dkrutsko** [mapbox/jsxtreme-markdown#34]
Hey there, `@mapbox/jsxtreme-markdown-loader` seems to be missing `prettier` from its `package.json` dependency list, leading to an error when using the webpack loader. Could you please add `prettier` to the dependency list in order to resolve this issue?

**Comment by davidtheclark** [comment]
Thanks, @dkrutsko! I guess we always had `prettier` installed in projects so missed this. Should be fixed in the latest releases, including 0.5.2 of `jsxtreme-markdown-loader`.
