### ISSUE TITLE
Front matter isn't getting parsed correctly

### ISSUE THREAD

**Issue by hugmanrique** [mapbox/jsxtreme-markdown#37]
Right now, passing this markdown fragment through `toJsx()` gives me an empty `frontMatter` object:
(Using v0.7.3)

```
---
title: Hello world
imports:
  test: './test.js'
---

# Hello world
```

**Comment by davidtheclark** [comment]
@hugmanrique Would you mind saying more about your usage? `toJsx` just returns a string, so I'm not sure I understand what you *expect* to happen that is not happening.

**Comment by hugmanrique** [comment]
I'm sorry, I meant `toComponentModule`

**Comment by davidtheclark** [comment]
@hugmanrique Please provide more details in a reduced test case: what code are you running, what is the expected behavior, and what is the behavior you're actually seeing.

**Comment by hugmanrique** [comment]
Passing the following string to `jsxtremeMarkdown.toComponentModule()`:

```markdown
---
title: Hello world
imports:
  test: './test.js'
---

# Hello world
```

produces this output:

```js
import React from "react";

const frontMatter = {};

export default class MarkdownReact extends React.PureComponent {
  render() {
    const props = this.props;
    return (
       <div>Hello world</div>
    );
  }
}
```

**Comment by davidtheclark** [comment]
@hugmanrique I just created a test with this Markdown file and go the expected result, with populated `frontMatter`. 🤔 

```js
test('hugmanrique test', () => {
  const text = prepText(`
    ---
    title: Hello world
    imports:
      test: './test.js'
    ---

    # Hello world
  `);

  const code = toComponentModule(text);
  expect(code).toMatchSnapshot();
});
```

```
// Snapshot
"/*---
title: Hello world
imports:
  test: './test.js'
---*/
import React from \\"react\\";

const frontMatter = {
  title: \\"Hello world\\",
  imports: {
    test: \\"./test.js\\"
  }
};

export default class MarkdownReact extends React.PureComponent {
  render() {
    const props = this.props;
    return <h1>Hello world</h1>;
  }
}
"
```

If you can provide a way to reproduce this problem, I might be able to help. But it still looks to me like the function is working as expected.

**Comment by hugmanrique** [comment]
Ok, the issues was I wasn't removing the extra text indents as you do by using the `prepText` function. Thanks for your help! :)

**Comment by davidtheclark** [comment]
Glad we tracked it down!
