### ISSUE TITLE
How is this repo related to `remark-react`?

### ISSUE THREAD

**Issue by MathiasSM** [mapbox/jsxtreme-markdown#44]
I don't see this using the other. I'd like the plugin's `remarkReactComponents` option here, but can't get them to work together.

**Comment by davidtheclark** [comment]
@MathiasSM This repo is not right now related to remark-react, and doesn't use it. The `remarkReactComponents` option is a nice one, agreed: this project would have to independently implement it. Probably we'd need to add it as an option to `hast-util-to-jsx`, then add options exposing that functionality to the higher-level packages.
