### ISSUE TITLE
Can frontmatter be exported

### ISSUE THREAD

**Issue by zach-sim** [mapbox/jsxtreme-markdown#45]
I found this project through @hugmanrique/react-markdown-loader and a key difference appears to be that it override's the processing template to ```export const frontMatter``` instead of ```const frontMatter```.

Is there any reason why that specific change can't be implemented here?

**Comment by davidtheclark** [comment]
> Is there any reason why that specific change can't be implemented here?

Nope. In fact, you can do that right now by making a custom template https://github.com/mapbox/jsxtreme-markdown/tree/master/packages/jsxtreme-markdown#template
