### ISSUE TITLE
Maybe rename

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/jsxtreme-markdown#7]
The problem with the current name is that it *seems* specific and targeted but does not *actually* address the key feature here, which is the *interpolation of JS and JSX*.

@tristen is going to spend a lot of time thinking about good names for this tool, unless he tasks one of his subordinates with it.

**Comment by tristen** [comment]
One of the focus groups I command sent me this: `mbmarkdown-to-jsx`. Which isn't perfect - I've since fired most of them - but it's like whole different flavour of markdown for mapbox! "mbmarkdown"

**Comment by davidtheclark** [comment]
This led me to a great thought: `jsxtreme-markdown`. Like extreme sports but for Markdown and JSX, and inside at your computer.

**Comment by davidtheclark** [comment]
I've renamed it.
